from web.models import Session
from web.schemas import TrackingPointCreate


def tracking_point_payload(
    point: TrackingPointCreate,
    session: Session,
    *,
    point_id: str,
    aoi_id: str | None,
) -> dict:
    return {
        "point_id": point_id,
        "session_id": point.session_id,
        "user_id": point.user_id or session.user_id,
        "aoi_id": aoi_id,
        "course_id": point.course_id or session.course_id,
        "course_item_id": point.course_item_id or session.course_item_id,
        "pdf_lesson_id": point.pdf_lesson_id or session.pdf_lesson_id,
        "pdf_document_version": point.pdf_document_version or session.pdf_document_version,
        "test_id": point.test_id or session.test_id,
        "module_id": point.module_id or session.module_id,
        "activity_id": point.activity_id or session.activity_id,
        "content_version_id": point.content_version_id or session.content_version_id,
        "stimulus_id": point.stimulus_id,
        "timestamp_ms": point.timestamp_ms,
        "viewport_x": point.viewport_x if point.viewport_x is not None else point.x,
        "viewport_y": point.viewport_y if point.viewport_y is not None else point.y,
        "scroll_x": point.scroll_x,
        "scroll_y": point.scroll_y,
        "stimulus_x_norm": point.stimulus_x_norm,
        "stimulus_y_norm": point.stimulus_y_norm,
        "stimulus_left": point.stimulus_left,
        "stimulus_top": point.stimulus_top,
        "stimulus_width": point.stimulus_width,
        "stimulus_height": point.stimulus_height,
        "tracking_quality": point.tracking_quality,
        "screen_x": point.screen_x,
        "screen_y": point.screen_y,
        "viewport_width": point.viewport_width,
        "viewport_height": point.viewport_height,
        "device_pixel_ratio": point.device_pixel_ratio,
        "zoom": point.zoom,
        "fullscreen": point.fullscreen,
        "page_number": point.page_number,
        "page_x_normalized": point.page_x_normalized,
        "page_y_normalized": point.page_y_normalized,
        "page_display_width": point.page_display_width,
        "page_display_height": point.page_display_height,
        "confidence": point.confidence,
        "gaze_status": point.gaze_status,
        "metadata_json": point.metadata_json,
    }
