services:
  gaze-server:
    build:
      context: Gaze-Estimation
      dockerfile: Dockerfile
    image: eyetracking-image:gpu
    environment:
      device: cuda
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
