services:
  gaze-server:
    build: .
    image: eyetracking-image:latest
    container_name: eyetracking-container
    ports:
      - "9000:8000"
    volumes:
      - ./weights:/app/weights          # persist model calibration
    environment:
      - face_detector=yolo
      - face_detector_weight=weights/yolov8n-face.pt
      - gaze_estimator=unigaze
      - gaze_estimator_weight=weights/unigaze_l16_joint.safetensors
      - calibrator=svr
      - device=cuda
      - size=224
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    restart: unless-stopped 