services:
  gaze:
    image: hieunm1501/gaze-api:gpu
    ports:
      - "8000:8000"
    volumes:
      - ./weights:/app/weights
    environment:
      - DEVICE=cuda
    gpus: all
    restart: unless-stopped
